version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672" # RabbitMQ default port for AMQP
      - "15672:15672" # RabbitMQ Management Console
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - ku-wongnai

networks:
  ku-wongnai:
    driver: bridge
